
services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: api-proyect-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ci-network

  app:
    image: my-quarkus-app:latest
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native-micro
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/api-proyect-database
      QUARKUS_DATASOURCE_USERNAME: myuser
      QUARKUS_DATASOURCE_PASSWORD: mypassword
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500" # Interfaz web de Consul
      - "8600:8600/udp" # DNS de Consul
    volumes:
      - ./config/consul/config:/etc/consul.d # Monta el directorio de configuración
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -config-dir=/etc/consul.d

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    ports:
      - "5500:5500"
      - "9500:9500"
    volumes:
      - ./pipelines/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8100:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Users\lanth\Desktop\Project-ApiRest\src\main\resources\privateKey.pem:/var/jenkins_home/privateKey.pem
      - C:\Users\lanth\Desktop\Project-ApiRest\src\main\resources\publicKey.pem:/var/jenkins_home/publicKey.pem
      - C:\Users\lanth\Desktop\Project-ApiRest\src\main\resources\env:/var/jenkins_home/env
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    networks:
      - ci-network

  sonarqube:
      image: sonarqube:lts
      container_name: sonarqube
      ports:
        - "9000:9000"
      environment:
        - SONARQUBE_JDBC_USERNAME=sonar
        - SONARQUBE_JDBC_PASSWORD=sonar
        - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/api-proyect-database
      depends_on:
        - postgres
      networks:
        - ci-network


volumes:
  postgres_data:
  jenkins_home:

networks:
  elk:
    driver: bridge
  ci-network: