version: '3.8'
services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: my-quarkus-app:latest
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native-micro
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/mydatabase
      QUARKUS_DATASOURCE_USERNAME: myuser
      QUARKUS_DATASOURCE_PASSWORD: mypassword
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: